services:
  web:
    build: .
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
